[package]
name = "air-elt-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
autotests = false

[lib]
name = "air_elt_app"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "air-elt"
path = "src/main.rs"

[dependencies]
air-elt-core = { workspace = true }
air-elt-commons = { workspace = true }
air-elt-commons-mongodb = { workspace = true }
air-elt-source-postgres = { workspace = true }
air-elt-source-mysql = { workspace = true }
air-elt-sink-postgres = { workspace = true }
air-elt-sink-mysql = { workspace = true }
air-elt-storage-postgres = { workspace = true }
air-elt-storage-mysql = { workspace = true }
air-elt-source-mongodb = { workspace = true }
air-elt-source-mongo-cdc = { workspace = true }
air-elt-sink-mongodb = { workspace = true }
air-elt-storage-mongodb = { workspace = true }
air-elt-sink-clickhouse = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
mimalloc = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
air-elt-commons-testing = { workspace = true }
sqlx = { workspace = true }
tempfile = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
bigdecimal = { workspace = true }
mongodb = { workspace = true }
bson = { workspace = true }
futures = { workspace = true }

[lints]
workspace = true

[[test]]
name = "all"
path = "tests/all.rs"
