[package]
name = "air-elt-commons-pg"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
air-elt-core = { workspace = true }
air-elt-commons = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
bigdecimal = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
