CREATE TABLE IF NOT EXISTS air_elt_cursors (
    flow       VARCHAR(255) NOT NULL PRIMARY KEY,
    state      JSON NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB;
