[package]
name = "air-elt-source-mongodb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
autotests = false

[lib]
doctest = false

[[test]]
name = "all"
path = "tests/all.rs"

[dependencies]
air-elt-core = { workspace = true }
air-elt-commons = { workspace = true }
air-elt-commons-mongodb = { workspace = true }
mongodb = { workspace = true }
bson = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
ahash = { workspace = true }

[dev-dependencies]
toml = { workspace = true }
air-elt-commons-testing = { workspace = true }
air-elt-sink-mongodb = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
