[package]
name = "air-elt-expr-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
air-elt-expr-parse = { workspace = true }
air-elt-expr-funcs = { workspace = true }
air-elt-expr-types = { workspace = true }
air-elt-expr-optimize = { workspace = true }
air-elt-types = { workspace = true }
ahash = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
test-strategy = { workspace = true }

[lints]
workspace = true
